CONTRIBUTING.rst
config/settings/base.py
metadeploy/conftest.py
metadeploy/management/commands/promote_superuser.py
metadeploy/management/commands/tests/promote_superuser.py
metadeploy/multisalesforce/management/commands/populate_social_apps.py
metadeploy/multisalesforce/management/commands/tests/populate_social_apps.py
pytest.ini
requirements/test.txt

[starting-data] 📦 Add management commands for social apps and superusers

---

src/js/components/header.js

Add aria-describedby to custom-domain-login.

---

config/settings/base.py
jest.config.js
metadeploy/context_processors.py
metadeploy/tests/context_processors.py
package.json
requirements/base.txt
requirements/production.txt
src/index.html
src/js/accounts/actions.js
src/js/components/header/login.js
src/js/index.js
src/js/raven.js
src/js/utils/api.js
src/js/utils/logging.js
test/js/accounts/actions.test.js
test/js/utils/logging.test.js
webpack.common.js
yarn.lock

[sentry] 🐈 Add Sentry error logging.

---

Procfile
requirements/production.txt

add newrelic monitoring to the production requirements and procfile

New Relic APM

---

metadeploy/api/migrations/0009_migrate_category_to_productcategory.py

🛢 Hotfix to migration

---

metadeploy/api/serializers.py

Get correct value for serializer

---

config/settings/base.py
config/settings/production.py

[hotfix-prod-settings] Find overridden templates in production settings

---

metadeploy/api/management/commands/tests/truncate_data.py
metadeploy/api/management/commands/truncate_data.py

This will delete all your `api.models` models in the correct order.

[truncate-data-command] Add truncate_data management command

---

.circleci/config.yml
Procfile

Also some minor fixes/improvements to CircleCI config.

[newrelic-rq] Add New Relic monitoring for django-rq worker/scheduler.

---

metadeploy/api/jobs.py
metadeploy/api/tests/jobs.py
requirements/base.txt

[github3] Move to use Github3.py

---

metadeploy/api/jobs.py

[github3-fix] Make safe-path more rigorous

---

Procfile
metadeploy/asgi.py

Run web process with daphne

---

metadeploy/api/models.py

Per fix in https://stackoverflow.com/questions/37764070/django-migrations-valueerror-could-not-find-manager-in-django-db-models-manager.
(my dog picture was too large, so heres some procedurally generated content)

Correctly use Manager.from_queryset

---

.eslintrc.yml
package.json
src/js/components/plans/stepsTable/installDataCell.js
yarn.lock

So my working theory is that the build was failing because the various linting tasks were running in parallel and taking too long. This changes to run them serially.

🐈 Upgrade deps and hopefully fix CI.

---

package.json

Try running flow separately?

---

config/settings/base.py
metadeploy/multisalesforce/tests/views.py
metadeploy/multisalesforce/views.py

[structured-log-lines] Add structured log lines

---

config/settings/base.py
metadeploy/logfmt.py
metadeploy/logging_middleware.py
metadeploy/tests/logfmt.py
requirements/base.txt

[http-logging] Log Heroku request ID

---

config/settings/local.py
requirements/local.txt

📦 use django-extensions on local only

---

.coveragerc
CONTRIBUTING.rst
metadeploy/management/commands/get_sf_token.py
metadeploy/management/commands/tests/get_sf_token.py
metadeploy/tests/integration.py
package.json
pytest.ini
requirements/local.txt

[integration-tests] 📦 Add basic integration tests that touch an SF org

---

src/js/components/plans/ctaButton.js
src/js/components/plans/detail.js
src/js/index.js
test/js/components/plans/detail.test.js

[signal-no-permissions] Show warning when current user lacks org permissions

---

requirements/base.txt

[rq-scheduler-pin] 📦 Hold back rq-scheduler

---

metadeploy/api/jobs.py

[hotfix-canceled-job] Treat canceled job as canceled, not failed.

---

src/js/components/jobs/detail.js
src/js/components/jobs/progressIndicator.js
src/js/components/plans/detail.js
src/js/components/plans/header.js
src/js/components/plans/progressIndicator.js
src/js/plans/reducer.js
test/js/components/jobs/progressIndicator.test.js
test/js/components/plans/progressIndicator.test.js

[progress-indicator] Add progress-indicator to installation page.

---

config/settings/base.py

respect the `DJANGO_ADMIN_URL`

use admin area env var

---

locales/en/translation.json
locales_dev/en/translation.json
metadeploy/api/models.py
metadeploy/api/tests/models.py
src/js/components/error.js
src/js/components/products/detail.js
src/js/store/plans/selectors.js
src/js/store/products/reducer.js
test/js/components/products/detail.test.js

@jgerigmeyer can you help me with the test for the new branch?

Handle no primary plan (and fix spelling)

---

requirements/base.txt

This should fix the heroku deployment

📦 Update sfdo-template-helpers

---

CONTRIBUTING.rst
metadeploy/api/management/commands/populate_data.py
src/js/components/jobs/detail.js
src/js/components/products/list.js
test/js/components/products/list.test.js

Addresses minor cleanup for two stories:
- https://trello.com/c/z0JQnmrI
- https://trello.com/c/02T6vVvf

[cleanup-product-categories] Address review/demo feedback.

---

metadeploy/adminapi/api.py
metadeploy/adminapi/tests/api.py

django-filters doesn't know what to do with an ImageField

Fix products admin API

---

metadeploy/adminapi/api.py

Make the product filters actually work

---

config/settings/base.py
metadeploy/api/jobs.py

[improve-background-task-logging] Show error tracebacks from background jobs

---

src/js/components/plans/stepsTable/index.js
src/js/components/plans/stepsTable/installDataCell.js
test/js/components/plans/detail.test.js
test/js/components/plans/stepsTable.test.js

[checkbox-clarity] Remove disabled checkboxes.

---

src/js/components/plans/toasts.js
src/sass/patterns/_containers.scss
src/sass/patterns/_manifest.scss

Trello: https://trello.com/c/ZGlV9fQT/129-bug-cannot-click-on-header-login-logout-logo-when-toast-is-visible

[narrow-toast] Add max-width to toasts.

---

config/settings/production.py
metadeploy/api/jobs.py
metadeploy/rq_worker.py

This will hopefully fix warm shutdown of jobs when dynos restart.

Use HerokuWorker in production

---

metadeploy/api/permissions.py
metadeploy/api/views.py

See https://trello.com/c/D2rQ3bYe/136-as-salesforce-staff-i-need-to-be-able-to-cancel-another-users-job

[superuser-can-delete] Super user can cancel anyone's jobs

---

babel.config.js
requirements/base.txt

📦 Upgrade deps to silence warnings.

---

metadeploy/urls.py
src/js/index.js

Closes #272 
https://trello.com/c/6BK48BQC/139-address-i18n-feedback-on-language-loading

Omit static dir from client-serving fallback

---

src/js/components/products/detail.js

Trello story: https://trello.com/c/1ZjDy7jl

[markdown] hides header if header in markdown

---

src/js/components/plans/stepsTable/requiredDataCell.js
src/sass/components/_steps.scss

see: https://trello.com/c/1ZjDy7jl

[optional-steps-clarity] optional steps are highlighted yellow

---

src/js/store/user/actions.js

[hotfix-ws-reconnect] Resubscribe to user/org after websocket reconnect.

---

.circleci/config.yml
package.json
requirements/base.txt
src/js/components/products/notAllowed.js
yarn.lock

[hotfix-custom-restricted] Restrict width of custom restricted-access message.

---

app.json

The app.json didn't have the CONNECTED_APP_CLIENT_ID environment variable which prevented deployment using the Deploy to Heroku button.

Add CONNECTED_APP_CLIENT_ID

---

.circleci/config.yml
requirements/base.txt

A picture of a cute microbe, because this change is so small.

[fix-sfdo-python-dep] 📦 Make sfdo-template-helpers not editable

---

.circleci/config.yml
requirements/base.txt
requirements/test.txt

Just a quick requirements update.

[sfdo-t-h-update] 📦 Update version of SFDO Template Helpers

---

config/settings/test.py
metadeploy/api/push.py
metadeploy/api/tests/push.py
metadeploy/consumer_utils.py
metadeploy/consumers.py
metadeploy/tests/consumers.py
metadeploy/tests/layer_utils.py

This just sets a semaphore in Redis where the message is set, and pulls it where the message is read.
See https://trello.com/c/2abLmB1E/140-consider-debouncing-throttling-websocket-events

[debounce-websockets] Debounce websockets

---

config/settings/base.py
metadeploy/api/models.py

See https://github.com/SFDO-Tooling/MetaDeploy/pull/265#pullrequestreview-234704309

[improve-average-duration] Use median for "average duration"

---

metadeploy/api/management/commands/populate_data.py
metadeploy/api/management/commands/tests/populate_data.py

THIS RUNS FOR REAL. Be warned.

[realistic-plan] Add EDA to sample data

---

src/js/store/jobs/actions.js
src/js/store/plans/actions.js
test/js/store/jobs/actions.test.js

https://oddbird.slack.com/archives/CB2576XT4/p1557426417013800

[hotfix-api-error] Anticipate possible `null` API response.

---

Procfile
manage.py
metadeploy/asgi.py
metadeploy/rq_worker.py
metadeploy/tests/rq_worker.py
package.json
requirements/base.txt
requirements/production.txt

It needs a bit of help to work with Channels and with rq.

Fix newrelic instrumentation

---

locales/en/translation.json
locales_dev/en/translation.json
src/js/components/plans/ctaButton.js
src/js/components/plans/stepsTable/index.js
src/js/components/plans/stepsTable/nameDataCell.js
test/js/components/plans/ctaButton.test.js

[resolve-warning] Make preflight warnings clearer.

---

requirements/base.txt

This seems to help us get the intended version of requests 😱(possibly because it puts cumulusci higher, which pins all of its dependencies to exact versions)

📦 Sort requirements

---

metadeploy/api/jobs.py
metadeploy/api/tests/jobs.py
requirements/base.txt

Small change to make sure we have info to debug edge cases with the metadata API

📦 Record metadata API response if it's attached to a job exception

---

metadeploy/api/paginators.py

[hotfix-pagination] Use pagination value from env var.

---

metadeploy/api/models.py
requirements/base.txt

[use-new-slug-models] 📦 Use sfdo-template-helpers slugs

---

.circleci/config.yml
package.json
src/index.html
test/js/utils/api.test.js
yarn.lock

🐈 [upgrade-slds] Upgrade SLDS; cleanup circleCI env vars

---

flow-typed/npm/@salesforce/design-system-react_vx.x.x.js
package.json
src/js/components/header/index.js
src/js/components/jobs/detail.js
src/js/components/plans/header.js
src/sass/components/_header.scss
yarn.lock

🐈 Upgrade react-slds

---

flow-typed/npm/react-redux_v7.x.x.js
package.json
yarn.lock

Greenkeeper/webpack 4.36.1

---

package.json
yarn.lock

🐈 Upgrade front end deps.

---

.browserslistrc
.pyup.yml
app.json
docs/conf.py
metadeploy/urls.py
package.json
src/index.html
yarn.lock

Clean up deployment and upgrade deps.

---

requirements/base.txt

Try disabling pyopenssl (which is no longer needed) to see if that gives any clarity into the ECONNRESET issue

📦 try without pyopenssl

---

requirements/base.txt

Trying another thing, to avoid reusing old connections

📦 Trigger a new build

---

requirements/base.txt

* Updates that came out yesterday.

python dependency updates

---

requirements/base.txt

including a fix for preflight checks

📦 Use CumulusCI master

---

config/settings/base.py
metadeploy/api/push.py
requirements/base.txt

Fixes an issue where the frontend wasn't receiving push notifications, and adds some logging to help track down issues in the future.

📦 Update channels-redis; add logging of push messages

---

metadeploy/api/migrations/0085_update_socialapps.py

The last attempt with savepoints didn't fix the error; let's see if this does

try a different way

---

requirements/base.txt

This includes the fix for sandbox logins.

bump our dependency

---

src/js/components/footer.tsx
test/js/components/footer.test.js

Work.com asked for the ability to not show this. /cc @shibinkunnath

Only show copyright in footer if configured in the SiteProfile

---

metadeploy/adminapi/translations.py
metadeploy/api/admin.py
metadeploy/api/models.py

1. Make it possible to load SiteProfile translations
2. Make it possible to search the Transation model in the admin

Adjustments for translation machinery

---

metadeploy/api/admin.py

Make jobs searchable by job_id

---

.heroku/check_change_traffic_control.py
.heroku/release.sh

1. refactoring
2. actually enforce the check
3. don't run the db migration until we've confirmed there is an approved change case

Updates to change traffic control check

---

metadeploy/api/admin.py

fix error when trying to search Preflight Results in the admin

---

config/settings/base.py
config/settings/test.py
metadeploy/api/management/commands/schedule_release_test.py
metadeploy/api/management/tests/commands.py

* Use `HEROKU_APP_NAME` instead of `HEROKU_WORKER_APP_NAME`.

Use different env var name

---

config/settings/base.py

add allauth setting to avoid interstitial page

---

config/settings/base.py

* Increase the timeout on the short queue to 300 seconds.

Fix broken job

---

metadeploy/api/models.py
metadeploy/tests/consumers.py

* Fixed a bug where re-running expired preflight checks would hang indefinitely.

Fix bug when re-running expired preflight checks

---

locales_dev/en/translation.json
src/js/components/jobs/progressBar.tsx
test/js/components/jobs/progressBar.test.js

Move the SLDS assistive text to the element designated as the label. This acts as a dynamic progress indicator, and gives users a better experience.

Assistive Text update for progress indicator

---

metadeploy/api/models.py
metadeploy/tests/consumers.py

Reverts SFDO-Tooling/MetaDeploy#3423

Revert "Fix bug when re-running expired preflight checks"

---

.pyup.yml

Remove .pyup.yml

---

metadeploy/api/github.py
metadeploy/api/tests/test_github.py

Use endswith instead of contains

---

src/js/components/bodyContainer.tsx
src/js/components/jobs/progressBar.tsx
src/js/components/jobs/userInfo.tsx
src/js/components/plans/intro.tsx
src/js/components/plans/stepsTable/index.tsx
src/js/components/plans/userInfo.tsx
src/js/components/products/detail.tsx
src/js/components/products/list.tsx
src/js/components/products/listItem.tsx
src/js/components/products/planCards.tsx

Accessibility bug : the default font is set to 13px as of now, as per the guidelines setting it to 16px.
Adding screenshots for review

Accessibility : font size set to default 16px as mentioned in the accessibility bug WI: W-11149812
