SFDO-Tooling/MetaDeploy

metadeploy/api/tests/templatetags_api_bootstrap.py
They'll be imported, as part of the templatetags magic, and make things fall down in staging or production environments without test requirements installed.
=> [templatetags-hotfix] Pull tests out of templatetags

metadeploy/multisalesforce/tests/views.py, metadeploy/multisalesforce/views.py
Now we store custom domain in the session.
This way it will persist across the OAuth conversation, and can be used in the OAuth callback on the MetaDeploy side to get a token from the Salesforce side.
=> [fix-custom-domain-login] Fix custom-domain login

config/settings/base.py
I've already set the env variables on staging; you won't need them on local dev.
=> [https-always] Add settings to always use HTTPS

config/settings/base.py, metadeploy/logfmt.py, metadeploy/tests/logfmt.py
Attach a logging filter (ala [using filters to impart contextual information](https://docs.python.org/2/howto/logging-cookbook.html#using-filters-to-impart-contextual-information), the same technique used by django_log_request_id) to the rq_console logging handler. It adds the current job_id to the JobRecord if we're in a job.
=> log rq job id when in a job

config/settings/base.py, package.json
Maybe also run `redis-cli FLUSHALL` before running the server to clear out old things?
=> [add-queue-result-ttl] Add default result TTL to queues

metadeploy/api/models.py
Things like get_by_natural_key that work on a standard Django user model now work on our user model.
=> use default manager for User

metadeploy/api/models.py, metadeploy/api/tests/models.py
See https://trello.com/c/5esBWARK/49-as-an-admin-i-dont-want-credentials-for-my-org-to-persist-longer-than-they-have-to
=> [flush-credentials] Exclude users with uninfished jobs from token expiry

metadeploy/api/cci_configs.py, metadeploy/api/jobs.py, metadeploy/api/tests/jobs.py
This PR fixes the issue we were seeing in production by making sure that everything needed for repo_info is populated before we construct the project config. It additionally switches us to using the "runtime"/"context" object 
There's some...separation of concerns concerns, and it's all around repo-ish details and how they get passed between the two objects. I think that things are slightly easier to mock, now, but still could be adjusted.
=> [repoctx] CumulusCI Context

metadeploy/api/jobs.py
If a repo URL is redirected to a new location, we need to look at the new names in the zipball.
=> Handle redirected repositories

config/settings/base.py
This tells django-storages to let the S3 objects inherit permissions from the bucket rather than setting per-object permissions (which our AWS user doesn't have permission to do)
=> Fix S3 uploads by avoiding setting per-object permissions

metadeploy/adminapi/api.py, metadeploy/adminapi/tests/api.py, metadeploy/conftest.py
Without this we were getting a 500 because we haven't set up an API route for users.
=> fix AllowedListOrg serializer to stringify users

.circleci/config.yml, requirements/base.txt
Reverts SFDO-Tooling/MetaDeploy#297
> The heroku buildpack uses an old version of pip that doesn't know how to install pep 517-style packages
https://github.com/heroku/heroku-buildpack-python/issues/796
=> Revert "[fix-sfdo-python-dep] 📦 Make sfdo-template-helpers not editable"

src/sass/components/_steps.scss
No Trello story, this is in response to:
https://github.com/SFDO-Tooling/MetaDeploy/pull/258#discussion_r281338128
Original Trello story for Install Logs: https://trello.com/c/pnXbwwSW/101-as-an-admin-i-want-to-view-the-logs-while-running-a-preflight-installation
=> [post-logs-styles] Simplify styles from install-logs branch

metadeploy/api/migrations/0073_allowedlist_list_for_allowed_by_orgs.py, metadeploy/api/models.py
Make it private by default.
(I'm intentionally modifying the existing migration rather than creating a new one because it hasn't been run on production yet.)
=> 🛢 Better default for list_for_allowed_by_orgs

metadeploy/api/jobs.py, metadeploy/api/models.py, metadeploy/api/tests/jobs.py, metadeploy/api/tests/models.py
The previous approach was doing a separate query to delete the SocialToken for each user (except users with recent logins or running jobs) and was taking longer and longer as we accumulate users. This changes it so we're primarily querying tokens (which should always be a fairly short list) and then doing separate queries for each token to confirm the user doesn't have running jobs.
I imagine it's possible to do it as a single query but this is probably good enough.
=> Optimize expiration of tokens

metadeploy/api/jobs.py, metadeploy/api/serializers.py, metadeploy/api/tests/jobs.py, metadeploy/api/tests/serializers.py
Some improvements to error handling:
1. Validate that the user still has a valid token before scheduling a job. (This is https://trello.com/c/imvWSpW8/155-check-for-valid-token-before-scheduling-job; I still don't really understand how the user can get here since the expiration of the token should remove their access to the install button, but there's evidence that it happens.)
2. Provide a more friendly message when a job is canceled due to the worker dyno restarting.
3. Don't mark the rq job as failed if the job is canceled by user request.
=> Better error handling for expired tokens and dyno restarts

metadeploy/api/serializers.py
This was preventing plans from being listed on the product detail page if the user's org has access via the allowed list org type
(For example, log into https://install.salesforce.org/products/sal with a scratch org)
=> Don't pay attention to list_for_allowed_by_orgs for plans

package.json, src/js/components/plans/clickThroughAgreementModal.js, src/js/components/plans/preflightWarningModal.js, yarn.lock
I'm not sure when this regression was introduced, but this PR fixes a bug where after confirming the preflight-with-warnings modal, it stays open and overlaps with the click-through-agreement modal (see https://metadeploy-devstaging.herokuapp.com/products/product-with-useful-data/0.3.1/preflight-with-warnings):
=> [hotfix-plan-modals] Close plan modals on Confirm.

requirements/base.txt
@wlonk I see on MetaShare we're using the latest versions of these packages. Upgrading seems to work for me locally -- can you confirm whether or not we can safely remove these PyUp restrictions?
=> 📦 [upgrade-py-deps] Remove pyup dep limitations.

metadeploy/api/push.py, metadeploy/consumer_utils.py, metadeploy/consumers.py, metadeploy/tests/layer_utils.py, src/js/store/org/actions.js, src/js/store/org/reducer.js, test/js/store/org/reducer.test.js
* Include group name in the message so a semaphore for one model doesn't prevent delivery of the same message about a different model
* Expire redis key after 5 seconds so it doesn't prevent future messages if this one goes unreceived
* Remove the workaround I was using to make sure the frontend found out preflight was complete even if the ORG_CHANGED message was not delivered
=> Fixes for websocket semaphore

Procfile, metadeploy/api/management/commands/populate_data.py, package.json
This tells the rqscheduler to put repeatable jobs in the "short" queue instead of the default queue.
The scheduler seems to ignore the queue name that is configured on the RepeatableJob records. And the way we were passing queue names to rqscheduler before was also ignored.
I confirmed that jobs enqueued using the delay method (such as the actual preflight and flow runs) still end up in the default queue.
This does mean that it's not possible to set up a RepeatableJob that will use the default queue, which is annoying, but not actually a problem for this project.
=> The non-build jobs belong in the short queue

metadeploy/api/admin.py, requirements/base.txt
- Temporarily switch to CumulusCI master to include SFDO-Tooling/CumulusCI#1190
- Show created_at field in the PreflightResult admin listing
=> A couple small fixes

metadeploy/api/admin.py, metadeploy/api/flows.py, metadeploy/api/tests/flows.py
path is not guaranteed to be unique because there can be multiple invocations of the same task name in one flow.
I'm keeping the lookup by path when processing preflight results because that's what CumulusCI gives us -- we'll want to fix this too but not as quickly since it requires coordination between packages.
=> Locate steps in the db by step_num instead of path

requirements/base.txt, requirements/test.txt, yarn.lock
I think there are still a couple missing updates for the JS dependencies that `yarn upgrade-interactive` didn't pickup without the `--latest` flag. I can circle back once this is merged and see what dependabot is still complaining about.
=> Dependabot updates 11-04-2019

src/js/components/header/customDomainModal.js, src/js/utils/api.js, test/js/components/header/customDomainModal.test.js, test/js/utils/api.test.js
When testing installers I'd like to be able to paste:
https://efficiency-app-148.cs78.my.salesforce.com/
into the custom domain modal, but this results in:
https://https://efficiency-app-148.cs78.my.salesforce.com/.my.salesforce.com
and a `400 Bad Request`. This PR updates `customDomainModal` to
instead remove the protocol and domain to produce the expected output:
https://efficiency-app-148.cs78.my.salesforce.com
=> Update custom domain modal to remove protocol and domain

config/settings/base.py
In testing on metadeploy staging I found an error that was caused by new plans getting created with their language code set to "en" rather than "en-us". I think this should help.
=> Update LANGUAGES to match LANGUAGE_CODE

config/settings/base.py, docs/running_docker.rst, env.example
Use safer defaults for https-related settings. SECURE_SSL_REDIRECT is the master switch; if it is on then the others should default to being on as well.
=> Default TLS-related settings based on SECURE_SSL_REDIRECT

metadeploy/adminapi/api.py, metadeploy/adminapi/tests/translations.py, metadeploy/adminapi/translations.py, metadeploy/api/admin.py
update_all_translations can take a while; let's run it in an rq job so it doesn't hold up requests.
I also added a language filter to the Admin UI for the Translation model
=> Update translations in an rq job

metadeploy/api/jobs.py, metadeploy/api/models.py, metadeploy/api/tests/jobs.py, metadeploy/api/tests/models.py, metadeploy/tests/integration.py
This fixes a bug where the wrong step could be skipped if it shared a step path with another step.
=> Use step_num instead of path to identify skipped steps

config/settings/base.py, metadeploy/api/jobs.py, metadeploy/api/tests/jobs.py, requirements/base.txt
Allows for either `GITHUB_TOKEN` to be used with a personal access token or `GITHUB_APP_ID` and `GITHUB_APP_KEY` for using a GitHub App.
- Removed the setting of the github service in the constructed keychain since CumulusCI now will use the `GITHUB_*` environment variables rather than fetching the service from the keychain if the environment variables are set
NOTE: This won't work for any of the github_* tasks in CumulusCI as BaseGithubTask requires that the github service is set in the keychain.  This should be addressed in CumulusCI to have a more intelligent check that checks if the GITHUB_* environment variables are set and falls back to checking the keychain if not.  However, that change isn't required for this PR since MetaDeploy plans typically don't use the github_* tasks from …
=> Allow use of GitHub App

locales/en/translation.json, locales_dev/en/translation.json
Capitalize the recommended string for MetaDeploy UI to look nicer in the UI.
Discussed this with @jlantz yesterday. From the code search, it is used only in one file for which I believe it is ok to capitalize. But please check and let me know if we're good to go ahead with this change.
Current screenshot where it is not capital
=> Capitalize the recommended string for MetaDeploy UI

metadeploy/api/cleanup.py, metadeploy/api/models.py, metadeploy/api/tests/cleanup.py, package.json, src/js/components/plans/stepsTable/installDataCell.tsx, yarn.lock
It turns out we can't delete SocialAccount so soon because it's an important part of maintaining the connection between an oauth login and a user. Instead, return to deleting the SocialToken, and also clear out the SocialAccount's extra_data.
=> Fix connection between SocialAccount and User

metadeploy/api/jobs.py
cci needs an OrgConfig with a username set in order to complete JWT auth for a connected org. (And for other things, but that's what revealed that it's missing.) This is a fairly recent regression from the work on the scratch org feature, and hasn't affected production because we haven't set SFDX_HUB_KEY there yet, so cci is still using the refresh token flow there.
=> fix jwt auth for connected orgs

metadeploy/adminapi/translations.py
This fixes it so that we use this label in the same cases where the metadeploy_publish task generates it. Before, a label like "Install foo" would be left alone by metadeploy_publish, but MetaDeploy would still convert it to "Install {product} {version}" and look for a translation that doesn't exist.
=> Only use the generic Install {product} {version} label when the default value ends with a number

config/settings/base.py, metadeploy/tests/views.py, metadeploy/urls.py, metadeploy/views.py
* MetaDeploy now has `custom_500_view` which has default messages for both generic 500 errors as well as when MetaDeploy detects that IP Login Ranges are in place for a user. The message displayed for IP Login Range errors can be overridden by setting the `IP_RESTRICTED_MESSAGE` config variable in Heroku.
=> Gracefully handle ip restriction errors when logging in

README.rst, config/settings/base.py
Received an error when publishing a product to MetaDeploy `Could not update ca-es translation: 404 Client Error: Not Found for url: https://metadeploy.herokuapp.com/cuteanimals/rest/translations/ca-es`
This will add support for Catalonian Spanish to the list
=> Add Catalan Spanish to language list.

metadeploy/api/models.py
When a MetaDeploy plan is run that includes preflight checks with the `skip` action, and the conditions are met to skip that step, MetaDeploy presents an error:
> Invalid steps for plan
This PR aims to fix the issue by correcting the identification of optional steps to include those in `SKIP` status.
=> Treat skipped steps as optional for validity

metadeploy/api/models.py, metadeploy/api/tests/serializers.py
"A model’s Meta.ordering doesn’t affect GROUP BY queries." https://docs.djangoproject.com/en/3.2/releases/3.1/#features-removed-in-3-1
=> Fix ordering of products

metadeploy/api/jobs.py
cumulusci 3.38.0 added a built-in connected_app service as the default in the keychain, so adding metadeploy's service is no longer setting it as the implicit default. So let's do that explicitly.
=> make sure metadeploy's connected app is set as the default

metadeploy/api/push.py, metadeploy/logfmt.py, metadeploy/tests/logfmt.py
1. Log pushing of messages to websockets at debug level so it's less noisy
2. Call the request_id the same thing that the Heroku router does
=> A couple tweaks to logging

metadeploy/api/jobs.py, metadeploy/api/tests/jobs.py, metadeploy/conftest.py
Log when jobs and preflight checks complete with various statuses for ingestion into metrics.
Partially dependent on W-9935537 (for new fields).
=> Job and preflight completion logging

metadeploy/api/jobs.py, metadeploy/api/tests/jobs.py, metadeploy/logfmt.py, metadeploy/logging_middleware.py, metadeploy/tests/logfmt.py
- Make sure the event field is emitted at the beginning of the log line (needed in order to be turned into a metric by our log drain app)
- Provide a more human-friendly msg field
- Fixed a number of issues with quoting of logfmt field values
- Removed tag field, which we weren't using
=> Adjustments to job logging

metadeploy/api/jobs.py, metadeploy/api/tests/jobs.py
(so that I don't have to figure out how to make rsyslog parse quoted fields correctly right now)
=> avoid spaces in the logged context for job events

metadeploy/api/flows.py, metadeploy/api/jobs.py, metadeploy/api/tests/flows.py, metadeploy/api/tests/jobs.py
Also make sure that unhandled exceptions from both Jobs and Preflights store a traceback in the exception field.
As an example, before this change, we merely got an unhelpful line in the `log` field: Exception in task get_installed_packages
Now we get a full traceback and error message in the `exception` field:
=> Make sure unhandled exceptions in preflight tasks get logged

metadeploy/api/management/commands/run_plan.py, metadeploy/api/management/tests/commands.py
We now log an error message along with additional context if a failure during scratch org creation occurs.
=> Log error and context on scratch org creation failure

config/settings/base.py
(True used to be the default, but that changed in django-allauth 0.48.0)
=> set SOCIALACCOUNT_STORE_TOKENS = True 

README.rst, requirements/prod.in, requirements/prod.txt
CCI 3.55 has a fix for an old flow-step syntax needed by V4S.
=> CCI 3.55 for Flow syntax fix

config/settings/base.py, metadeploy/management/commands/metadeploy_rqscheduler.py, metadeploy/management/commands/tests/test_metadeploy_rqscheduler.py
* We now allow CRON_JOBS to specify a `queue_name`.
* Switched the `calculate_average_plan_runtime` job to run on the default queue.
=> Allow queue overrides in cron jobs

.slugignore
This PR adds a .slugignore file to exclude some files from MDP's slug. [Docs]
[Docs]: https://devcenter.heroku.com/articles/slug-compiler#ignoring-files-with-slugignore
=> Add .slugignore

src/js/components/header/index.tsx, test/js/components/header/index.test.js
Use company name for logo alt test instead of site name
Fixes: [W-11149764](https://gus.lightning.force.com/a07EE00000x9uxkYAA)
=> Use company name for company logo as alt text

config/settings/base.py, metadeploy/api/salesforce.py
MetaDeploy stops polling for scratch org creation after the default job timeout length.
=> Apply job timeout to scratch org polling

manage.py, metadeploy/asgi.py, metadeploy/rq_worker.py, metadeploy/tests/rq_worker.py, requirements/prod.in, requirements/prod.txt
Why?:
1. The last update broke the app.
2. We're not using it.
We think it's related to newrelic/newrelic-python-agent#584, but see (2) above.
=> Remove newrelic-python-agent

.readthedocs.yaml
We've been using an outdated python version and requirements file for a couple years.
* Include a `.readthedocs.yaml` file which specifies the version of Python to use when building docs, as well as, which requirements file to use.
=> Fix readthedocs

.heroku/start_metadeploy_worker.sh, Procfile, docs/vbt-lwc-compiler.md, package.json, yarn.lock
Make a [new script](https://github.com/SFDO-Tooling/MetaDeploy/pull/3468/files#diff-568838017c33edbf49458e93c994c192f6c774bae92d345172ad082e3b144983R1) that makes Chrome available to the VBT compiler.
Invoke it from [Procfile](https://github.com/SFDO-Tooling/MetaDeploy/pull/3468/files#diff-0a99231995da379e7aebabe76c9d849a23737a42c3b3a8994043e2aa80958424R3). 
Install Vlocity and Upgrade "[MiniPass](https://github.com/SFDO-Tooling/MetaDeploy/pull/3468/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)" to work around a bug that seems to have arisen asynchronously (perhaps the type declarations are downloaded at runtime).
=> Use Puppeteer VBT compiler in workers

metadeploy/api/github.py, metadeploy/api/tests/test_github.py
This fixes a bug where a product that has a repository name that is a substring of another repository name causes an error when invoking the `github_local_checkout()` method.
=> Make product filtering more specific

locales_dev/en/translation.json, src/js/components/products/listItem.tsx
added an aria-label for the link surrounding a product card
See #W-11149827
A couple of things I'm not sure of:
* I set the aria-label on the Link component. Other choices were the outer div or the inner Card. 
* I set the label text to be "Product Link: <product name> version <version>". Is that too wordy?
* I only added a translation for "Product Link:" rather than the entire label. Is that correct or should the entire string be translated?
=> added an aria-label for the link surrounding a product card

src/js/components/header/index.tsx
In order to remove the additional h1 tag in the global header of the app, the use of the `<PageHeader>` component was removed in favor of generic SLDS markup.
=> Remove use of PageHeader component in global header section

config/settings/base.py, docs/scheduled_jobs.md, metadeploy/api/cleanup.py, metadeploy/api/tests/test_cleanup.py
* API Tokens are now expired after 30 days. The number of days can be configured by setting the `API_TOKEN_EXPIRE_AFTER_DAYS` environment variable.
=> Expire Tenant API Tokens

manage.py, metadeploy/api/github.py, metadeploy/api/tests/test_github.py, metadeploy/api/tests/test_jobs.py, src/js/components/plans/header.tsx
This removes the link from the name of the product in the plan page. 
See [W-11149809](https://gus.lightning.force.com/a07EE00000xA3mBYAS)
According to an a11y audit, the contrast was too low and the link was redundant since there's a link further down the page. Turning off the link improved the contrast.
=> Remove link from the breadcrumb on plan pages

config/settings/base.py, docs/scheduled_jobs.md, metadeploy/api/cleanup.py, metadeploy/api/tests/test_cleanup.py, metadeploy/conftest.py
We now expire Admin API Tokens after 30 days.
=> Expire API Tokens

src/sass/components/_steps.scss
Increased contrast of background for step log. Using `$brand-dark-active` design token from SLDS.
Before:
After:
Contrast check:
=> Make Plan Step log more accessible

src/js/components/header/logout.tsx, src/sass/components/_header.scss
The Logout menu did not read the username when selected using a screen-reader. I had to implement a workaround to modify the CSS of the disabled menu item, so it visually didn't have any changes, but would read the username for screen readers.
Before:
After:
=> Implement workaround for dropdown component. Fixes W-11149825.

locales/en/translation.json, locales_dev/en/translation.json, src/js/components/backLink.tsx, src/js/components/jobs/ctaButton.tsx
Add assistive text to 'view org' button to alert screen reader users the link opens in a new window. 
Before:
After:
Removed redundant assistive text from 'install another product' link.
Before:
After:
=> Clean up assistive text for "view org" and "install another product" links.

metadeploy/api/tests/test_views.py, metadeploy/api/views.py
* MetaDeploy now serves the contents of `staticfiles/django_js_reverse/js/reverse.js` under the `/api/ui/reverse` endpoint.
=> Make Contents of `django-js-reverse` available via API.

src/js/components/plans/intro.tsx
Small but impactful change.
Before this change, the small alrts above the call to action button would not be announced by a screenreader and a screen reader user would not be aware of the messages.
After the change the alerts are recognized and read by the screen reader:
I just managed to grab this screenshot before the toast itself was also read.
=> Add alert div around messages to enable screen reader announcement 

metadeploy/api/jobs.py, metadeploy/api/tests/test_jobs.py
* Fixed a bug where a preflight job stuck in a `started` status due to a dyno restart would block user's from re-running preflight checks.
The manifestation of this bug in the UI was a little confusing. Both "Pre-install validation completed successfully" and "A pre-install validation is currently running on this org" were displayed in the UI at the same time. Because preflights default `is_valid=True`, the front-end picks up the `is_valid` and displays the "completed" message, while the "currently running" message is shown because of the preflight associated with the user's org is still in a "started" status. The `expire_preflights` job now looks for preflights with a status of `started` that are older than 10 minutes. If this status is detected, then it is updated to `canceled`.
=> Fix Stalled Preflights

src/js/components/header/login.tsx
change from 'overflowBoundaryElement' to 'absolute' for dropdown posi…tion in login button component. The fixes an a11y bug preventing mobile voiceover users from accessing the dropdown menu due to the dropdown menu being rendered in a detached render tree
=> Modify dropdown config for login component

env.example
Having the mock DB_ENCRYPTION_KEY in env.example resulted in false
positives during static analysis. This commit removes the mock key, and
improves documentation by including a working one-liner to generate a
valid fernet key.
=> Remove mock DB_ENCRYPTION_KEY

.github/setup-docker-compose/action.yml, .github/workflows/test.yml, .github/workflows/upgrade-deps.yml, .npmrc, Dockerfile, docker-compose.yml, package.json, yarn.lock
Required to support [local compilation] of FlexCards in Vlocity CLI. This requires the addition of a private NPM repository to allow the installation of the compiler via:
```console
yarn add @omniscript/omniscript-lwc-compiler
```
Should allow faster deployment of OmniStudio components.
[heroku docs]: https://devcenter.heroku.com/articles/nodejs-support#private-dependencies
[local compilation]: https://github.com/vlocityinc/vlocity_build#initial-support-for-omniscript--flexcards-local-compilation
=> Add omniscript-lwc-compiler as dependency

sfdc_metadata/cred_scan_triage/triage.yaml
Grover flags the environment variable in .npmrc as a secret.
=> Add Credential Scan triage

package.json
External users may not have access to the Vlocity private NPM
repository, blocking them from installing front end dependencies. This
change allows yarn install to complete successfully.
=> Make Omnistudio local compiler optional

.github/workflows/deploy-storybook.yml, .github/workflows/smoke_test.yml, .github/workflows/test.yml, .github/workflows/upgrade-deps.yml
GitHub deprecated multiple labels for private runners.
=> Update Actions runner labels

metadeploy/routing.py
WebSockets can be initiated from any site on the internet and still have the user’s cookies and session. This pull request restricts the sites which are allowed to open sockets to the app.
See W-14666893
=> Validate websocket origin

.github/workflows/test.yml, Dockerfile, package.json, src/js/index.tsx, yarn.lock
- Update node version to latest LTS
- Copy/paste pyjs dockerfile
- temporarily ignore optional deps
- Pytest no longer on PATH
- Ignore tsc error
- Remove coverage step
- suppress eslint errors
=> fix: Update node and CI workflows
